# Generated by Django 3.1.3 on 2020-11-15 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20201115_0219'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
