# Generated by Django 3.1.3 on 2020-11-15 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20201115_0238'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='name_test',
            field=models.CharField(default='less', max_length=200),
        ),
    ]
