# Generated by Django 3.1.3 on 2020-11-21 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_customuser_name_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
